version: '2'
services:
  elasticsearch:
    build: ../devbox/es-related/dockerfiles/dev/elasticsearch/
    volumes:
      - ../devbox/es-related/dockerfiles/dev/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ../devbox/container-data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - aaronsweebook
  kibana:
    build: ../devbox/es-related/dockerfiles/dev/kibana/
    volumes:
      - ../devbox/es-related/dockerfiles/dev/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - aaronsweebook

networks:
  aaronsweebook:
    driver: bridge
